# Generated by Django 5.2.16 on 2026-07-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_code', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('rh_factor', models.CharField(choices=[('+', 'Positive (+)'), ('-', 'Negative (-)'), ('Null', 'Rh-null')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_code', models.CharField(max_length=30, unique=True)),
                ('donation_datetime', models.DateTimeField(help_text='Exact date/time the blood was drawn from the donor. This is the reference point used to calculate expiry for every component split from this donation.')),
                ('quantity_ml', models.PositiveIntegerField(help_text='Total whole-blood volume collected, in mL.')),
                ('status', models.CharField(choices=[('Collected', 'Collected'), ('Testing', 'Testing'), ('Passed', 'Passed - Units Released to Inventory'), ('Rejected', 'Rejected - Failed Screening'), ('Discarded', 'Discarded')], default='Collected', max_length=20)),
                ('units_generated', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
            ],
            options={
                'ordering': ['-donation_datetime'],
            },
        ),
    ]
