# Generated by Django 5.2.16 on 2026-08-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_fix_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donors_dona_status_9cb6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_datetime'], name='donors_dona_donatio_ae498e_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group', 'rh_factor'], name='donors_dono_blood_g_8073d0_idx'),
        ),
    ]
