# Generated by Django 5.2.16 on 2026-08-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donation_donors_dona_status_9cb6ba_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
