# Generated by Django 5.2.16 on 2026-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donation_donation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
