# Generated by Django 5.2.16 on 2026-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_donor_donor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='deferral_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_deferred',
            field=models.BooleanField(default=False, help_text='Flagged if donor has medical deferral or post-donation infection recall (e.g. HIV/Hepatitis).'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['is_deferred'], name='donors_dono_is_defe_02c945_idx'),
        ),
    ]
