# Generated by Django 5.2.15 on 2026-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donor_deferral_reason_donor_is_deferred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='donor',
            name='nin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='National Identity Number'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_datetime',
            field=models.DateTimeField(),
        ),
    ]
