# Generated by Django 5.2.15 on 2026-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_donor_age_donor_dob_donor_nin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='age',
        ),
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM-DD', max_length=10, null=True, verbose_name='Date of Birth (BS)'),
        ),
    ]
