# Generated by Django 5.2.16 on 2026-07-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Packed Red Blood Cells', 'Packed Red Blood Cells'), ('Fresh Frozen Plasma', 'Fresh Frozen Plasma'), ('Platelets', 'Platelets'), ('Cryoprecipitate', 'Cryoprecipitate')], max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('shelf_life_days', models.PositiveIntegerField(help_text='Days from collection until this component expires.')),
                ('ml_per_unit', models.PositiveIntegerField(default=450, help_text='mL that counts as "1 unit" of this component (e.g. 450 for a whole-blood/RBC bag, 200 for plasma).')),
                ('split_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='% of the original whole-blood donation volume that becomes this component when a donation passes lab screening and is auto-separated. Leave blank if this component is not produced by auto-separation (it can still be added to inventory manually).', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['component_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=40, unique=True)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('rh_factor', models.CharField(choices=[('+', 'Positive (+)'), ('-', 'Negative (-)'), ('Null', 'Rh-null')], max_length=10)),
                ('quantity_ml', models.PositiveIntegerField()),
                ('collected_at', models.DateTimeField(blank=True, help_text='When the blood was actually drawn. Auto-filled from the linked donation if left blank. This is what expiry is calculated from, not the date it was tested or shelved.', null=True)),
                ('expiry_date', models.DateField(blank=True, editable=False, help_text="Calculated automatically: collection date + the component's shelf life. Not editable directly.", null=True)),
                ('unit_state', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Issued', 'Issued'), ('Expired', 'Expired'), ('Discarded', 'Discarded')], default='Available', max_length=20)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bloodcomponent')),
                ('donation', models.ForeignKey(blank=True, help_text='Source donation. When set, the collection date/time and expiry are taken from the donation automatically.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='donors.donation')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField()),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_status', models.CharField(default='Available', max_length=20)),
                ('blood_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.bloodunit')),
            ],
        ),
    ]
