# Generated by Django 5.2.16 on 2026-07-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['component_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=40, unique=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('rh_factor', models.CharField(max_length=10)),
                ('quantity_ml', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('unit_state', models.CharField(default='Available', max_length=20)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bloodcomponent')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField()),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_status', models.CharField(default='Available', max_length=20)),
                ('blood_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.bloodunit')),
            ],
        ),
    ]
