# Generated by Django 5.2.16 on 2026-08-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donation_donors_dona_status_9cb6ba_idx_and_more'),
        ('inventory', '0003_fix_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bloodunit',
            index=models.Index(fields=['unit_state', 'expiry_date'], name='inventory_b_unit_st_9a4fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodunit',
            index=models.Index(fields=['blood_group', 'rh_factor', 'unit_state'], name='inventory_b_blood_g_0e4b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['storage_status'], name='inventory_i_storage_d90d7f_idx'),
        ),
    ]
