# Generated by Django 5.2.16 on 2026-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bloodunit_inventory_b_unit_st_9a4fd0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodunit',
            name='unit_code',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
