# Generated by Django 5.2.16 on 2026-07-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abo_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('rh_factor', models.CharField(choices=[('+', 'Positive (+)'), ('-', 'Negative (-)'), ('Null', 'Rh-null')], max_length=10)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, help_text='g/dL. Auto-fails below 12.5 g/dL.', max_digits=5, null=True)),
                ('hiv_result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('hbv_result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('hcv_result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('syphilis_result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('malaria_result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('overall_result', models.CharField(choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Pending', editable=False, help_text='Calculated automatically from the results above.', max_length=10)),
                ('tested_at', models.DateTimeField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donation')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
