# Generated by Django 5.2.16 on 2026-07-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abo_group', models.CharField(max_length=5)),
                ('rh_factor', models.CharField(max_length=10)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hiv_result', models.CharField(default='Pending', max_length=20)),
                ('hbv_result', models.CharField(default='Pending', max_length=20)),
                ('hcv_result', models.CharField(default='Pending', max_length=20)),
                ('syphilis_result', models.CharField(default='Pending', max_length=20)),
                ('malaria_result', models.CharField(default='Pending', max_length=20)),
                ('overall_result', models.CharField(default='Pass', max_length=10)),
                ('tested_at', models.DateTimeField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donation')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
