# Generated by Django 5.2.16 on 2026-08-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donation_donors_dona_status_9cb6ba_idx_and_more'),
        ('lab', '0002_fix_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bloodtest',
            index=models.Index(fields=['overall_result'], name='lab_bloodte_overall_b3abea_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodtest',
            index=models.Index(fields=['tested_at'], name='lab_bloodte_tested__6b8183_idx'),
        ),
    ]
