# Generated by Django 5.2.16 on 2026-07-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=30, unique=True)),
                ('required_blood_group', models.CharField(max_length=5)),
                ('required_rh', models.CharField(max_length=10)),
                ('required_component', models.CharField(max_length=60)),
                ('units_required', models.PositiveIntegerField(default=1)),
                ('request_status', models.CharField(default='Pending', max_length=20)),
                ('request_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Crossmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crossmatch_code', models.CharField(max_length=30, unique=True)),
                ('compatibility_result', models.CharField(default='Compatible', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('crossmatched_at', models.DateTimeField()),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.bloodrequest')),
            ],
            options={
                'ordering': ['-crossmatched_at'],
            },
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=30, unique=True)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('issued_datetime', models.DateTimeField()),
                ('issue_status', models.CharField(default='Issued', max_length=20)),
                ('crossmatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.crossmatch')),
                ('issued_to_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-issued_datetime'],
            },
        ),
    ]
