# Generated by Django 5.2.16 on 2026-07-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(max_length=30, unique=True)),
                ('required_blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('required_rh', models.CharField(choices=[('+', 'Positive (+)'), ('-', 'Negative (-)'), ('Null', 'Rh-null')], max_length=10)),
                ('units_required', models.PositiveIntegerField(default=1)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending - Awaiting Match'), ('Booked', 'Booked - Unit Reserved'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField()),
                ('required_component', models.ForeignKey(help_text='Which component the patient needs (RBC, Plasma, etc.).', on_delete=django.db.models.deletion.PROTECT, to='inventory.bloodcomponent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Crossmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crossmatch_code', models.CharField(max_length=30, unique=True)),
                ('crossmatch_status', models.CharField(choices=[('Booked', 'Booked - Awaiting Test'), ('Passed', 'Passed - Ready to Issue'), ('Failed', 'Failed - Incompatible'), ('Released', 'Released - Reservation Expired'), ('Issued', 'Issued')], default='Booked', editable=False, max_length=20)),
                ('compatibility_result', models.CharField(choices=[('Pending', 'Pending'), ('Compatible', 'Compatible'), ('Incompatible', 'Incompatible')], default='Pending', editable=False, max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_until', models.DateTimeField(blank=True, editable=False, help_text='Auto-set to 48h after booking. The reservation is released automatically if the unit is not issued before this time.', null=True)),
                ('crossmatched_at', models.DateTimeField(blank=True, editable=False, help_text='Set automatically when the compatibility test is recorded.', null=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.bloodrequest')),
                ('blood_unit', models.ForeignKey(help_text='The inventory unit booked/reserved for this request.', on_delete=django.db.models.deletion.PROTECT, related_name='crossmatches', to='inventory.bloodunit')),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=30, unique=True)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('issued_datetime', models.DateTimeField()),
                ('issue_status', models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20)),
                ('crossmatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.crossmatch')),
                ('issued_to_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-issued_datetime'],
            },
        ),
    ]
