# Generated by Django 5.2.16 on 2026-08-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bloodunit_inventory_b_unit_st_9a4fd0_idx_and_more'),
        ('patients', '0002_fix_schema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bloodissue',
            index=models.Index(fields=['issue_status', 'issued_datetime'], name='patients_bl_issue_s_30c48c_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['request_status', 'request_date'], name='patients_bl_request_d05472_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequest',
            index=models.Index(fields=['required_blood_group', 'required_rh', 'request_status'], name='patients_bl_require_12d80c_idx'),
        ),
        migrations.AddIndex(
            model_name='crossmatch',
            index=models.Index(fields=['crossmatch_status', 'reserved_until'], name='patients_cr_crossma_fcfa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'),
        ),
    ]
