# Generated by Django 5.2.16 on 2026-08-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_bloodissue_patients_bl_issue_s_30c48c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodissue',
            name='issue_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='crossmatch',
            name='crossmatch_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
