# Generated by Django 5.2.15 on 2026-08-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_bloodissue_issue_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Medical Record Number'),
        ),
    ]
